[package]
name = "crain"
version = "0.1.0"
edition = "2021"
authors = ["BaiChuanByte <baichuanbyte@outlook.com>"]

description = "A Brainfuck compiler/interpreter/tool"
license = "MIT"

[dependencies]
thiserror = "1.0"
